#!/bin/bash
# ensure-server-actions-key.sh — ensure NEXT_SERVER_ACTIONS_ENCRYPTION_KEY
# is persisted in .env so Next.js Server Actions survive PM2 restarts +
# rebuilds without orphaning encrypted action references from prior
# client bundles.
#
# WHAT IT FIXES (task #149 — v2.52.6):
#   Without a persistent encryption key, Next.js auto-generates a random
#   one per build. Client bundles compiled with key K1 send encrypted
#   action references that can ONLY be decrypted by a server running K1.
#   After PM2 restart following a `npm run build` (which reads a new
#   random key from process memory each time the build process starts),
#   the new server has K2 — every in-flight or cached browser tab
#   submitting an action gets "Failed to find Server Action 'X'".
#   Holmgren logged exactly that error 2026-05-19 05:52 after the v2.52.1
#   restart cascaded across 6 boxes.
#
# WHAT IT DOES NOT FIX:
#   This only helps for builds AFTER the key is persisted. Existing
#   client bundles in browser caches will still fail until those tabs
#   reload (1-time hit per browser). Future builds use the persisted
#   key → no more stale-action errors.
#
# IDEMPOTENT: if the key is already set in .env, exits cleanly with no
# change. Run as part of auto-update.sh's preflight.
#
# WHY PER-LOCATION: each location's box gets its OWN key (encryption
# boundary per location). Generated locally on first run; persists
# in .env which is gitignored. Operators do NOT need to know this key
# — it's app-internal.

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/ubuntu/Sports-Bar-TV-Controller}"
ENV_FILE="$REPO_ROOT/.env"
KEY_NAME="NEXT_SERVER_ACTIONS_ENCRYPTION_KEY"

# If no .env file at all, create one (location bootstrap may not have).
if [ ! -f "$ENV_FILE" ]; then
  touch "$ENV_FILE"
  chmod 600 "$ENV_FILE"
fi

# Already set? Done.
if grep -qE "^${KEY_NAME}=" "$ENV_FILE" 2>/dev/null; then
  echo "[ensure-server-actions-key] $KEY_NAME already set in .env — no change"
  exit 0
fi

# Generate a 32-byte base64-encoded random key (44 chars). Next.js
# accepts any length but documents 32 bytes as the recommended size.
KEY_VALUE=$(openssl rand -base64 32 2>/dev/null)
if [ -z "$KEY_VALUE" ]; then
  echo "[ensure-server-actions-key] ERROR: openssl rand failed — cannot generate key" >&2
  exit 1
fi

# Append. Use a newline boundary so we don't merge into an existing
# trailing line.
{
  # Ensure trailing newline before appending
  if [ -s "$ENV_FILE" ] && [ "$(tail -c1 "$ENV_FILE" | wc -l)" -eq 0 ]; then
    echo ""
  fi
  echo "# Persistent encryption key for Next.js Server Actions (v2.52.6)."
  echo "# Generated by scripts/ensure-server-actions-key.sh. DO NOT change"
  echo "# unless you accept that all in-browser tabs need to reload."
  echo "${KEY_NAME}=${KEY_VALUE}"
} >> "$ENV_FILE"

echo "[ensure-server-actions-key] Generated + persisted $KEY_NAME (44-char base64) to .env"
echo "[ensure-server-actions-key] Future builds will read this same key — Server Actions stable across PM2 restarts."
