#!/bin/bash
#
# CEC Device Setup Script
# Discovers Pulse-Eight adapters and generates udev rules for persistent device naming
#

set -e

echo "========================================"
echo "CEC Device Setup Wizard"
echo "========================================"
echo ""

# Check if cec-client is installed
if ! command -v cec-client &> /dev/null; then
    echo "❌ Error: cec-client not found"
    echo "Please install: sudo apt-get install cec-utils"
    exit 1
fi

echo "✓ CEC client found"
echo ""

# Discover all CEC adapters
echo "Scanning for Pulse-Eight USB CEC adapters..."
echo ""

ADAPTERS=$(cec-client -l 2>/dev/null | grep "com port:" | awk '{print $3}')

if [ -z "$ADAPTERS" ]; then
    echo "❌ No CEC adapters found"
    echo "Please connect your Pulse-Eight USB CEC adapters and try again"
    exit 1
fi

echo "Found the following adapters:"
echo ""

ADAPTER_COUNT=0
declare -a ADAPTER_PATHS
declare -a ADAPTER_SERIALS

for adapter in $ADAPTERS; do
    ADAPTER_COUNT=$((ADAPTER_COUNT + 1))
    ADAPTER_PATHS+=("$adapter")

    # Try to get serial number
    SERIAL=$(udevadm info -q property -n $adapter 2>/dev/null | grep ID_SERIAL_SHORT | cut -d'=' -f2)
    if [ -z "$SERIAL" ]; then
        SERIAL="unknown"
    fi
    ADAPTER_SERIALS+=("$SERIAL")

    echo "  $ADAPTER_COUNT. $adapter (Serial: $SERIAL)"
done

echo ""
echo "Total adapters found: $ADAPTER_COUNT"
echo ""

# Generate udev rules
UDEV_FILE="/etc/udev/rules.d/99-pulse-eight-cec.rules"

echo "Generating udev rules for persistent device naming..."
echo ""

# Create temporary rules file
TEMP_RULES=$(mktemp)

cat > $TEMP_RULES << 'EOF'
# Pulse-Eight USB CEC Adapter Rules
# Auto-generated by setup-cec-devices.sh
#
# This file creates persistent device names for Pulse-Eight adapters
# based on their USB port location or serial number
#

EOF

# Add rules for each adapter
for i in "${!ADAPTER_PATHS[@]}"; do
    adapter="${ADAPTER_PATHS[$i]}"
    serial="${ADAPTER_SERIALS[$i]}"
    device_num=$((i + 1))

    # Get USB path (supports both direct USB and hub paths)
    # Direct USB: 3-7
    # Hub USB: 3-7.1, 3-7.2, etc.
    USB_PATH=$(udevadm info -a -n $adapter 2>/dev/null | grep 'KERNELS==' | head -1 | sed 's/.*KERNELS=="\([^"]*\)".*/\1/')

    # Check if serial is unique (not just version number like "v12")
    # Serials like "v12" are firmware versions, not unique IDs
    IS_UNIQUE_SERIAL=false
    if [ "$serial" != "unknown" ] && [ ${#serial} -gt 5 ]; then
        IS_UNIQUE_SERIAL=true
    fi

    if [ "$IS_UNIQUE_SERIAL" = true ]; then
        # Rule based on serial number (preferred, but only if truly unique)
        echo "# Adapter $device_num - Serial: $serial" >> $TEMP_RULES
        echo "SUBSYSTEM==\"tty\", ATTRS{serial}==\"$serial\", SYMLINK+=\"cec-adapter-$device_num\"" >> $TEMP_RULES
    elif [ ! -z "$USB_PATH" ]; then
        # Rule based on USB port (works for both direct and hub)
        echo "# Adapter $device_num - USB Path: $USB_PATH" >> $TEMP_RULES
        echo "SUBSYSTEM==\"tty\", KERNELS==\"$USB_PATH\", SYMLINK+=\"cec-adapter-$device_num\"" >> $TEMP_RULES

        # Add helpful comment about hub setup
        if [[ $USB_PATH == *"."* ]]; then
            echo "# Hub-connected adapter - MUST stay in this hub port" >> $TEMP_RULES
        fi
    else
        echo "# Adapter $device_num - Could not determine unique identifier" >> $TEMP_RULES
    fi
    echo "" >> $TEMP_RULES
done

echo "Generated udev rules:"
echo "----------------------------------------"
cat $TEMP_RULES
echo "----------------------------------------"
echo ""

# Ask for confirmation
read -p "Install these udev rules to $UDEV_FILE? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo cp $TEMP_RULES $UDEV_FILE
    sudo udevadm control --reload-rules
    sudo udevadm trigger

    echo "✓ udev rules installed successfully"
    echo ""
    echo "Persistent device names created:"
    for i in $(seq 1 $ADAPTER_COUNT); do
        echo "  /dev/cec-adapter-$i"
    done
    echo ""
    echo "These devices will persist across reboots."
else
    echo "Installation cancelled"
fi

rm $TEMP_RULES

echo ""
echo "========================================"
echo "Next Steps:"
echo "========================================"
echo ""
echo "1. Update database with device paths:"
echo "   UPDATE CECDevice SET devicePath = '/dev/cec-adapter-1' WHERE id = 'cec-tv-power';"
echo "   UPDATE CECDevice SET devicePath = '/dev/cec-adapter-2' WHERE id = 'cec-cable-1';"
echo "   (etc.)"
echo ""
echo "2. Test connections via admin panel:"
echo "   http://localhost:3001/admin/cec-devices"
echo ""
echo "3. Start using the cable box remote:"
echo "   http://localhost:3001/cable-box-remote"
echo ""
