#!/usr/bin/env bash
#
# One-time MediaMTX install for OBSBOT Tail 2 camera video streaming
# (docs/OBSBOT_TAIL_2_PLAN.md). Downloads the MediaMTX static binary,
# writes a per-camera stream-proxy config, and installs it as a systemd
# --user unit (mirrors scripts/watchers/sports-bar-error-watch.service's
# style — Type=simple, Restart=always, journal logging).
#
# MediaMTX bridges the camera's RTSP source to LL-HLS the bartender iPad's
# Safari plays natively: Tail 2 (rtsp://<ip>:PORT/PATH) -> MediaMTX ->
# LL-HLS (:8888/<path>/index.m3u8).
#
# PORT/PATH DEFAULTS ARE UNRELIABLE — VERIFY PER CAMERA. OBSBOT's own docs
# say rtsp://<ip>:8554/live, but the first real unit (Lime Kiln, 2026-07-02,
# server banner "Remo RTSP Streaming Media Server/1.0.0") actually served on
# the RTSP-standard port 554 at path /stream1 — 8554/live connection-refused
# entirely. Probe before trusting the defaults below:
#   for p in 554 8554; do nc -zv <camera-ip> $p; done
#   printf 'DESCRIBE rtsp://<ip>:<port>/<path> RTSP/1.0\r\nCSeq: 1\r\n\r\n' | nc <camera-ip> <port>
#   (loop candidate paths — /live, /stream1, /stream, / — watch for "200 OK" vs "400 Bad Request")
#
# No root required — installs to $HOME/.local/bin and runs as a --user
# systemd unit under the ubuntu account, same as the error-watch/auto-update
# --user units. Requires `loginctl enable-linger ubuntu` to already be set
# (Gotcha #11) so the unit survives SSH logout — this script checks but
# does not set it (that's a root action owned by enforce-gotcha11-hardening.sh).
#
# Idempotent — safe to re-run (e.g. to add a second camera's path later).
#
# Usage:
#   bash scripts/setup-mediamtx.sh <camera-name> <camera-rtsp-ip> [rtsp-port] [rtsp-path]
#   bash scripts/setup-mediamtx.sh limekiln-cam1 192.168.5.103 554 /stream1
#
set -euo pipefail

CAMERA_PATH="${1:?Usage: setup-mediamtx.sh <mediamtx-path-name> <camera-ip> [rtsp-port] [rtsp-path]}"
CAMERA_IP="${2:?Usage: setup-mediamtx.sh <mediamtx-path-name> <camera-ip> [rtsp-port] [rtsp-path]}"
RTSP_PORT="${3:-8554}"
RTSP_PATH="${4:-/live}"

BIN_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/mediamtx"
CONFIG_FILE="$CONFIG_DIR/mediamtx.yml"
UNIT_DIR="$HOME/.config/systemd/user"
UNIT_FILE="$UNIT_DIR/mediamtx.service"
MEDIAMTX_BIN="$BIN_DIR/mediamtx"

log() { echo "[setup-mediamtx] $*"; }

log "Step 1/5: check linger (Gotcha #11 — required for a --user unit to survive SSH logout)"
if loginctl show-user "$(whoami)" 2>/dev/null | grep -q "Linger=yes"; then
  log "✓ linger enabled"
else
  log "⚠ linger NOT enabled — this unit will die when your SSH session ends."
  log "  Fix (needs root): sudo loginctl enable-linger $(whoami)"
fi

log "Step 2/5: install MediaMTX binary"
mkdir -p "$BIN_DIR"
if [[ -x "$MEDIAMTX_BIN" ]]; then
  log "✓ already installed: $($MEDIAMTX_BIN --version 2>&1 | head -1 || echo present)"
else
  LATEST_URL=$(curl -s https://api.github.com/repos/bluenviron/mediamtx/releases/latest \
    | grep -oE '"browser_download_url": "[^"]+linux_amd64\.tar\.gz"' \
    | head -1 | cut -d'"' -f4)
  if [[ -z "$LATEST_URL" ]]; then
    log "✗ could not resolve latest MediaMTX release URL from GitHub API"
    exit 1
  fi
  log "  downloading $LATEST_URL"
  TMP_TAR=$(mktemp)
  curl -sL "$LATEST_URL" -o "$TMP_TAR"
  tar xzf "$TMP_TAR" -C "$BIN_DIR" mediamtx
  chmod +x "$MEDIAMTX_BIN"
  rm -f "$TMP_TAR"
  log "✓ installed: $($MEDIAMTX_BIN --version 2>&1 | head -1 || echo present)"
fi

log "Step 3/5: write/update mediamtx.yml (adds/updates the '$CAMERA_PATH' path)"
mkdir -p "$CONFIG_DIR"
if [[ ! -f "$CONFIG_FILE" ]]; then
  cat > "$CONFIG_FILE" <<EOF
# Generated by setup-mediamtx.sh — safe to hand-edit; re-running the script
# only touches the 'paths:' entry for the camera passed on the command line.
hls: yes
hlsAddress: :8888
hlsAllowOrigin: '*'
hlsVariant: lowLatency

paths:
  ${CAMERA_PATH}:
    source: rtsp://${CAMERA_IP}:${RTSP_PORT}${RTSP_PATH}
    sourceOnDemand: yes
    # TCP transport avoids "RTP packet too big for UDP" + massive packet
    # loss seen live on a 4K stream (Lime Kiln, 2026-07-02) — UDP RTP
    # datagrams have a hard size ceiling a high-bitrate H.264 stream
    # routinely exceeds. TCP-interleaved has no such limit.
    rtspTransport: tcp
EOF
  log "✓ wrote new $CONFIG_FILE"
else
  if grep -q "^  ${CAMERA_PATH}:" "$CONFIG_FILE"; then
    log "✓ path '$CAMERA_PATH' already present in $CONFIG_FILE (not modified — edit by hand if the source changed)"
  else
    cat >> "$CONFIG_FILE" <<EOF
  ${CAMERA_PATH}:
    source: rtsp://${CAMERA_IP}:${RTSP_PORT}${RTSP_PATH}
    sourceOnDemand: yes
    # TCP transport avoids "RTP packet too big for UDP" + massive packet
    # loss seen live on a 4K stream (Lime Kiln, 2026-07-02) — UDP RTP
    # datagrams have a hard size ceiling a high-bitrate H.264 stream
    # routinely exceeds. TCP-interleaved has no such limit.
    rtspTransport: tcp
EOF
    log "✓ appended path '$CAMERA_PATH' to existing $CONFIG_FILE"
  fi
fi

log "Step 4/5: install systemd --user unit"
mkdir -p "$UNIT_DIR"
cat > "$UNIT_FILE" <<EOF
[Unit]
Description=MediaMTX — RTSP to LL-HLS bridge for OBSBOT Tail 2 camera(s)
Documentation=https://github.com/dfultonthebar/Sports-Bar-TV-Controller/blob/main/docs/OBSBOT_TAIL_2_PLAN.md
After=default.target

[Service]
Type=simple
ExecStart=${MEDIAMTX_BIN} ${CONFIG_FILE}
Restart=always
RestartSec=15
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mediamtx

[Install]
WantedBy=default.target
EOF
log "✓ wrote $UNIT_FILE"

log "Step 5/5: daemon-reload + enable --now"
systemctl --user daemon-reload
systemctl --user enable --now mediamtx.service

sleep 2
echo
log "=== mediamtx.service status ==="
systemctl --user status mediamtx.service --no-pager 2>&1 | head -10 || true
echo
log "✅ Done. LL-HLS URL for this camera: http://<lan-ip>:8888/${CAMERA_PATH}/index.m3u8"
log "   (stream only pulls from the camera once a viewer connects — sourceOnDemand: yes)"
